TodoApp/Pages/Calendar.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using TodoApp.Areas.Identity.Data;
using TodoApp.Data;
using TodoApp.Models;

namespace TodoApp.Pages
{
    public class CalendarModel : PageModel
    {

        private readonly TodoDBContext _context;
        private readonly UserManager<User> _userManager;
        private readonly SignInManager<User> _signInManager;

        [BindProperty]
        public Todo Todo { get; set; } = default!;
        public IList<Todo> Todos { get; set; } = default!;

        public CalendarModel(TodoDBContext context, UserManager<User> userManager, SignInManager<User> signInManager)
        {
            _context = context;
            _userManager = userManager;
            _signInManager = signInManager;
        }

        public async Task OnGetAsync()
        {
            User? user = await _userManager.GetUserAsync(User);

            if (user != null)
            {
                TempData["User"] = user.Name;
                TempData["UserName"] = user.UserName;
            }

        }


        //handler for adding new task
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            Todo.LoggedInUserID = _userManager.GetUserId(User);

            _context.Todos.Add(Todo);
            await _context.SaveChangesAsync();

            return RedirectToPage("/TaskList/Index");
        }

        //Logout
        public async Task<IActionResult> OnPostLogoutAsync()
        {
            await _signInManager.SignOutAsync();
            return RedirectToPage("/Index");
        }

    }
}

TodoApp/Pages/Dashboard.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using TodoApp.Areas.Identity.Data;
using TodoApp.Data;
using TodoApp.Models;

namespace TodoApp.Pages
{
    public class DashboardModel : PageModel
    {
        private readonly TodoDBContext _context;
        private readonly SignInManager<User> _signInManager;
        private readonly UserManager<User> _userManager;

        public DashboardModel(TodoDBContext context, SignInManager<User> signInManager, UserManager<User>userManager)
        {
            _context = context;
            _signInManager = signInManager;
            _userManager = userManager;
        }

        public IList<Todo> CurrentUserTodos { get; set; }
        public IList<Todo> Todos { get; set; } = default!;

        public async Task OnGetAsync()
        {
            CurrentUserTodos = new List<Todo>();
            User? user = await _userManager.GetUserAsync(User);

            if (user != null)
            {

                var todos = await _context.Todos.ToListAsync();
                var sortedTodos = todos.OrderByDescending(x => x.CreatedOn).ToList();

                foreach (var todo in sortedTodos)
                {
                    if (todo.LoggedInUserID == user.Id)
                    {
                        CurrentUserTodos.Add(todo);
                    }
                }

                TempData["User"] = user.Name;
                TempData["UserName"] = user.UserName;

                Todos = CurrentUserTodos;

            }

        }

        [BindProperty]
        public Todo Todo { get; set; } = default!;
        public async Task<IActionResult> OnGetEditAsync(int? id)
        {
            Todo? todo = await _context.Todos.FirstOrDefaultAsync(m => m.TodoID == id);

            if (todo == null)
            {
                return NotFound();
            }


            return Partial("_UpdatePartialView", todo);
        }


        public async Task<IActionResult> OnPostEditAsync(Todo todo)
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }



            //check for updates made 

            if (todo.Status == "Started")
            {
                todo.IsActive = true;
            }
            else if (todo.Status == "Completed")
            {
                todo.IsCompleted = true;
                todo.CompletedOn = DateTime.Now;
            }
            else
            {
                todo.IsActive = false;
                todo.IsCompleted = false;
            }

            _context.Attach(todo).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!TodoExists(todo.TodoID))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("/Dashboard");
        }

        private bool TodoExists(int id)
        {
            return _context.Todos.Any(e => e.TodoID == id);
        }

        public async Task<IActionResult> OnPostDeleteAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var todo = await _context.Todos.FindAsync(id);
            if (todo != null)
            {
                _context.Todos.Remove(todo);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("/Dashboard");
        }

        //Logout
        public async Task<IActionResult> OnPostLogoutAsync()
        {
            await _signInManager.SignOutAsync();
            return RedirectToPage("/Index");
        }

    }
}

TodoApp/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace TodoApp.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }
        private string? ErrorMesage {  get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
            
        }
    }

}

TodoApp/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace TodoApp.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

TodoApp/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace TodoApp.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }

}

TodoApp/Pages/ProjectOverview.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using TodoApp.Areas.Identity.Data;
using TodoApp.Data;
using TodoApp.Models;

namespace TodoApp.Pages
{
    public class ProjectOverviewModel : PageModel
    {
        private readonly UserManager<User> _userManager;
        private readonly SignInManager<User> _signInManager;
        private readonly TodoDBContext _context;
        public ProjectOverviewModel(TodoDBContext context, UserManager<User> userManager, SignInManager<User> signInManager)
        {
            _context = context;
            _userManager = userManager;
            _signInManager = signInManager;
        }

        public IList<Todo> CurrentUserTodos { get; set; }
        public IList<Todo> Todos { get; set; } = default!;
        public async Task OnGet()
        {
            CurrentUserTodos = new List<Todo>();
            User? user = await _userManager.GetUserAsync(User);

            if (user != null)
            {

                var todos = await _context.Todos.ToListAsync();
                var sortedTodos = todos.OrderByDescending(x => x.CreatedOn).ToList();

                foreach (var todo in sortedTodos)
                {
                    if (todo.LoggedInUserID == user.Id)
                    {
                        CurrentUserTodos.Add(todo);
                    }
                }

                TempData["User"] = user.Name;
                TempData["UserName"] = user.UserName;

                Todos = CurrentUserTodos;

            }
        }

        public async Task<IActionResult> OnPostEditAsync(Todo todo)
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(todo).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!TodoExists(todo.TodoID))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("/ProjectOverview");
        }

        private bool TodoExists(int id)
        {
            return _context.Todos.Any(e => e.TodoID == id);
        }

        public async Task<IActionResult> OnPostDeleteAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var todo = await _context.Todos.FindAsync(id);
            if (todo != null)
            {
                _context.Todos.Remove(todo);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("/ProjectOverview");
        }

        //Logout
        public async Task<IActionResult> OnPostLogoutAsync()
        {
            await _signInManager.SignOutAsync();
            return RedirectToPage("/Index");
        }

    }
}

TodoApp/Pages/_UpdatePartialView.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using TodoApp.Data;
using TodoApp.Models;

namespace TodoApp.Pages
{
    public class _UpdatePartialViewModel : PageModel
    {
        private readonly TodoDBContext _context;

        public _UpdatePartialViewModel(TodoDBContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Todo? Todo { get; set; }

        public _UpdatePartialViewModel(Todo todo)
        {

            if (todo == null)
            {
                Todo = new Todo();
            }
            else
            {
                Todo = todo;
            }
        }
        public void OnGet()
        {

        }


    }
}

TodoApp/Pages/Calendar.cshtml
@page
@model CalendarModel
@using Models;

@{
    Layout = "_TaskViewLayout";
    ViewData["Title"] = "Calendar";
}

<section class="position-relative h-100">
    <div class="row flex-column flex-md-row h-100">
        <div class="col d-none d-lg-block col-lg-4 col-xl-3 p-0">
            <partial name="_SideBar" />
        </div>
        <div class="col col-lg-8 col-xl-9 p-0 | gradient-bg">
            <div class="container">
                <div id='calendar'></div>
            </div>

        </div>
    </div>
</section>

<section class="calendar-popup">
    <div class="modal fade" id="create-new-task-popup" tabindex="-1" aria-labelledby="createModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <p class="m-0">Add A New Task</p>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <form method="post" class="mb-4">
                    <div class="modal-body">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="bg-transparent | todo">
                            <div class="due | row align-items-center">
                                <div class="col">
                                    <i class="fa-solid fa-star"></i>
                                    <label asp-for="Todo.DueOn" class="control-label">Due date: </label>
                                </div>
                                <div class="col col-9">
                                    <input asp-for="Todo.DueOn" class="form-control bg-transparent border-0" type="text" />
                                </div>
                                <span asp-validation-for="Todo.DueOn" class="text-danger"></span>
                            </div>
                            <div class="card-details | row align-items-center">
                                    <div class="col">
                                        <i class="fa-solid fa-square-pen"></i>
                                        <label asp-for="Todo.Details" class="control-label">Details: </label>
                                    </div>
                                    <div class="col col-9">
                                        <input asp-for="Todo.Details" class="form-control bg-transparent border-0" placeholder="Type here..." />
                                    </div>
                                <span asp-validation-for="Todo.Details" class="text-danger"></span>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer | py-2 mt-4 ms-auto">
                        <button type="button" class="btn | close-btn" data-bs-dismiss="modal">Close</button>
                        <button class="btn | save-btn">Save changes</button>
                    </div>
                </form>

            </div>
        </div>
    </div>
</section>




@section Scripts {
    <script>
        //fullcalendar.io library
        document.addEventListener('DOMContentLoaded', function () {
            const calendarEl = document.getElementById('calendar')
            const calendar = new FullCalendar.Calendar(calendarEl, {
                initialView: 'dayGridMonth',
            })
            calendar.render();

            if (window.location.pathname == "/Calendar") {
                const calendar = document.getElementById("calendar");
                const calendarHeader = document.querySelector(".fc-header-toolbar");
                const calendarHeaderBtns = calendarHeader.getElementsByClassName("fc-toolbar-chunk")[2];
                const boxEls = Array.from(calendar.querySelectorAll("td.fc-day"));
                const dueDateInput = document.querySelector(".due input");

                calendar.addEventListener("click", (e) => {
                    if (e.target.closest("td")) {
                        const calendarDate = new Date(e.target.closest("td").querySelector("a").getAttribute('aria-label'));
                       
                        const month = String(calendarDate.getMonth() + 1).padStart(2, "0");
                        const day = calendarDate.getDate().toString().padStart(2, "0");
                        const year = calendarDate.getFullYear();

                        const currentTime = new Date().toLocaleTimeString("en-US", {
                            hour: "2-digit",
                            minute: "2-digit",
                            hour12: true
                        });

                        const currentDateVal = `${month}/${day}/${year} ${currentTime}`;

                        dueDateInput.value = currentDateVal;
                        $('#create-new-task-popup').modal("toggle");
                    }
                   
                });
            }

        });

    </script>

    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }



}

TodoApp/Pages/Dashboard.cshtml
@page
@model TodoApp.Pages.DashboardModel
@using Models;
@{
    Layout = "_TaskViewLayout";
    ViewData["Title"] = "Dashboard";

    int overdueTasksCount = 0;
    int completedTasksCount = 0;
    int weeklyTasksCount = 0;

    DateTime currentDate = DateTime.Now.Date;
    int daysToSubtract = (int)currentDate.DayOfWeek;

    if(Model.Todos != null && Model.Todos.Count > 0)
    {
        foreach (var task in Model.Todos)
        {
            DateTime firstDayOfWeek = new DateCalculations().FirstDayOfTheWeek;
            DateTime lastDayOfWeek = new DateCalculations().LastDayOfTheWeek;
            DateTime completedDate = task.CompletedOn.Date;
            DateTime dueDate = task.DueOn.Date;
            string? status = task.Status; 

            if (dueDate >= firstDayOfWeek && dueDate <= lastDayOfWeek)
            {
                weeklyTasksCount++;

                if (status == "Completed") completedTasksCount++;
                else if (status != "Completed" && DateTime.Now > dueDate) overdueTasksCount++;
                
            }
        }
    }

}

<section class="position-relative h-100 | dashboard-homepage">
    <div class="row h-100">
        <div class="col-3 p-0 | left-col-container">
            <partial name="_SideBar" />
        </div>
        <div class="col-9 p-3 text-center text-md-start | gradient-bg right-col-container">
            <div class="container">
                <div class="text-white | dashboard-header">
                    <partial name="_WelcomeText" />
                </div>
                <div class="weekly-accomplishment | row flex-column mb-5 flex-md-row">
                    <div class="week | col ">
                        <p class="fw-bold m-0 ">My week</p>
                    </div>
                    <div class="task-overdue | col">
                        <p class="m-0 ">(@weeklyTasksCount) Assigned Tasks</p>
                    </div>
                    <div class="task-ongoing | col">
                        <p class="m-0">(@overdueTasksCount) Overdue</p>
                    </div>
                    <div class="task-completed | col">
                        <p class="m-0">(@completedTasksCount) Completed</p>
                    </div>
                </div>
                <button class="fw-bold p-2 ps-0 m-0 border-0 bg-transparent | dropdown-btn">
                    <i class="fa-solid fa-angle-down"></i>
                    View Today's Task
                </button>

                <div class="tasks-container">
                    <div class="tasks-table | p-3">
                        <div class="table-body">
                            <div class="today-tasks">
                                <ul class="list-unstyled border-top">
                                    @if (Model.Todos != null && Model.Todos.Count > 0)
                                    {
                                        foreach (var task in Model.Todos)
                                        {
                                            var today = DateTime.Now;
                                            var currentTime = new TimeSpan(today.Hour, today.Minute, 0);
                                            if (task.DueOn.Date == today.Date)
                                            {
                                                <li class="border-bottom task-name">
                                                    <div class="row">
                                                        <div class="col">
                                                            <div class="d-flex justify-content-between align-items-center p-2">
                                                                <div class="content">
                                                                    <p class="m-0"> @task.Details</p>
                                                                    @{
                                                                        if (task.DueOn.TimeOfDay < currentTime)
                                                                        {
                                                                            <p class="fs-6 text-danger m-0">
                                                                                <span><i class="fa-regular fa-clock"></i></span>
                                                                                @task.DueOn.ToShortTimeString()
                                                                            </p>
                                                                        }
                                                                        else
                                                                        {
                                                                            <p class="fs-6 text-success m-0">
                                                                                <span><i class="fa-regular fa-clock"></i></span>
                                                                                @task.DueOn.ToShortTimeString()
                                                                            </p>
                                                                        }
                                                                    }

                                                                </div>


                                                                <button type="button" class="edit-btn border-0 p-1 px-2 rounded-2 opacity-0 bg-transparent" data-bs-toggle="modal" data-bs-target="@("#edit-popup-" + task.TodoID)">
                                                                    <i class="fa-solid fa-angle-right text-black"></i>
                                                                </button>

                                                            </div>

                                                        </div>

                                                        <partial name="_UpdatePartialView" model="new _UpdatePartialViewModel(task)" />

                                                    </div>

                                                </li>
                                            }

                                        }
                                    }
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

TodoApp/Pages/Index.cshtml
@page
@model IndexModel
@{
    Layout = null;
    ViewData["Title"] = "Home page";
}

<!DOCTYPE html>
<html lang="en" style="height:100%">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>

    <link rel="stylesheet" href="TodoApp.styles.css" asp-append-version="true" />
</head>
<body style="margin: 0; height: 100%">
    <div class="text-center | main-homepage">
        <div class="text-content">
            <h1 class="display-4">Let's get you started!</h1>
            <p>Start tracking and managing tasks to organize your every day life.</p>
        </div>
        <div class="ctas">
            <a href="/Identity/Account/Register" class="sign-up-btn">Sign up for an account</a>
            <p class="sign-in-text">Already have an account? <a href="Identity/Account/Login">Sign in here</a></p>
        </div>
    </div>
</body>

TodoApp/Pages/_UpdatePartialView.cshtml
@model _UpdatePartialViewModel;

<div class="modal fade" id="edit-popup-@Model.Todo.TodoID" tabindex="-1" aria-labelledby="editModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-fullscreen">
        <div class="modal-content">
            
                <div class="modal-header">
                <form asp-page-handler="Delete" asp-route-id="@Model.Todo.TodoID">
                    <button class="btn text-danger border-1 border-danger | delete-btn" onclick="confirm('You are about to delete this task. Go ahead?')">
                        <i class="fa-regular fa-trash-can"></i>
                        Delete task
                    </button>
                </form>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
            <form method="post" asp-page-handler="Edit" asp-route-id="Todo.TodoID">
                <input type="hidden" asp-for="Todo.TodoID">
                <div class="modal-body">
                    <div class="details | px-4 py-2">
                        <div class="form-group row align-items-center">
                            <div class="col-2">
                                <label asp-for="Todo.Details" class="fw-bold control-label"></label>
                            </div>
                            <div class="col-10">
                                <input asp-for="Todo.Details" class="text-black border-0 bg-transparent w-100 p-2 form-control" />
                                <span asp-validation-for="Todo.Details" class="text-danger"></span>
                            </div>

                        </div>
                        <div class="due | mb-3">
                            <div class="form-group row align-items-center">
                                <div class="col-2">
                                    <label asp-for="Todo.DueOn" class="fw-bold control-label"></label>
                                </div>
                                <div class="col-3">
                                    <input asp-for="Todo.DueOn" class="text-black border-0 bg-transparent w-100 p-2 form-control" />
                                    <span asp-validation-for="Todo.DueOn" class="text-danger"></span>
                                </div>

                            </div>
                        </div>
                        <div class="priority | mb-3">
                            <div class="priority-btn">
                                <div class="form-group row align-items-center">
                                    <div class="col-2">
                                        <label asp-for="Todo.Priority" class="fw-bold control-label"></label>
                                    </div>
                                 
                                    <div class="dropdown | col-3">
                                        <select asp-for="Todo.Priority" class="form-select" aria-label="Priority">
                                            <option value="" selected>Select</option>
                                            <option value="medium">Medium</option>
                                            <option value="high">High</option>
                                        </select>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="task-progress | mb-3">
                            <div class="progress-btn">
                                <div class="form-group row align-items-center">
                                    <div class="col-2">
                                        <label asp-for="Todo.Status" class="fw-bold control-label"></label>
                                    </div>

                                    <div class="dropdown | col-3">
                                        <select asp-for="Todo.Status" class="form-select" aria-label="Status">
                                            <option value="" selected>Select</option>
                                            <option value="Started">Started</option>
                                            <option value="Completed">Completed</option>
                                        </select>
                                    </div>
                                </div>
                            </div>
                        </div>
                        
                        <div class="description | mt-5">
                            <div class="form-group">
                                <label asp-for="Todo.Description" class="fw-bold control-label"></label>
                                <textarea asp-for="Todo.Description" rows="5" class="p-2 mt-2 w-100 rounded-3" placeholder="What is this task about?"></textarea>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer | py-2 mt-4 ms-auto">
                        <button type="button" class="btn | close-btn" data-bs-dismiss="modal">Close</button>
                        <button class="btn | save-btn">Save changes</button>
                </div>
            </form>
        </div>
    </div>
</div>